"""Help topic registry — all HELP content extracted from GameSession."""
from __future__ import annotations


def _box(title: str, lines: list[str]) -> str:
    width = 60
    out = [f"\n{'═' * width}", f"  {title}", f"{'─' * width}"]
    out += [f"  {l}" for l in lines]
    out.append("═" * width)
    return "\n".join(out)


_HELP_TOPICS: dict[str, str] = {
    # ── Navigation ────────────────────────────────────────────────────────────
    "LOOK": _box("HELP: LOOK", [
        "  Show the current room description, items, and exits.",
        "  Usage: LOOK  (or L)",
        "  Examples:",
        "    LOOK",
        "    L",
        "  See also: NORTH, SOUTH, EAST, WEST",
    ]),
    "L": _box("HELP: LOOK (L)", [
        "  Show the current room description, items, and exits.",
        "  Usage: LOOK  (or L)",
        "  Examples:",
        "    LOOK",
        "    L",
        "  See also: NORTH, SOUTH, EAST, WEST",
    ]),
    "LOOKMODE": _box("HELP: LOOKMODE", [
        "  Control how room descriptions are displayed when entering rooms.",
        "  Usage: LOOKMODE FULL | LOOKMODE QUICK",
        "",
        "  FULL  — Show complete room description (default)",
        "  QUICK — Show compact summary with highlights only",
        "",
        "  Quick look shows:",
        "    • Room name and available exits",
        "    • Items on the floor (green)",
        "    • Hostile enemies present (red)",
        "    • Recruitable NPCs (yellow)",
        "    • Other players in the room (blue)",
        "",
        "  Your preference is saved with your character.",
        "",
        "  See also: BATTLELOOK, LOOK",
    ]),
    "NORTH": _box("HELP: NORTH / SOUTH / EAST / WEST", [
        "  Move your party in the given direction.",
        "  Usage: NORTH / N, SOUTH / S, EAST / E, WEST / W",
        "  Details:",
        "    Moving costs 2 stamina per step.",
        "    Stamina 0 blocks movement until you rest.",
        "    Horses reduce stamina drain (HELP HORSES).",
        "  See also: LOOK, STAMINA, HORSES",
    ]),
    "SOUTH": _box("HELP: NORTH / SOUTH / EAST / WEST", [
        "  Move your party in the given direction.",
        "  Usage: NORTH / N, SOUTH / S, EAST / E, WEST / W",
        "  Details:",
        "    Moving costs 2 stamina per step.",
        "    Stamina 0 blocks movement until you rest.",
        "    Horses reduce stamina drain (HELP HORSES).",
        "  See also: LOOK, STAMINA, HORSES",
    ]),
    "EAST": _box("HELP: NORTH / SOUTH / EAST / WEST", [
        "  Move your party in the given direction.",
        "  Usage: NORTH / N, SOUTH / S, EAST / E, WEST / W",
        "  Details:",
        "    Moving costs 2 stamina per step.",
        "    Stamina 0 blocks movement until you rest.",
        "    Horses reduce stamina drain (HELP HORSES).",
        "  See also: LOOK, STAMINA, HORSES",
    ]),
    "WEST": _box("HELP: NORTH / SOUTH / EAST / WEST", [
        "  Move your party in the given direction.",
        "  Usage: NORTH / N, SOUTH / S, EAST / E, WEST / W",
        "  Details:",
        "    Moving costs 2 stamina per step.",
        "    Stamina 0 blocks movement until you rest.",
        "    Horses reduce stamina drain (HELP HORSES).",
        "  See also: LOOK, STAMINA, HORSES",
    ]),
    "EXAMINE": _box("HELP: EXAMINE", [
        "  Examine an item or NPC in detail.",
        "  Usage: EXAMINE <target>  (or X <target>)",
        "  Examples:",
        "    EXAMINE sword",
        "    X gareth",
        "  See also: LOOK, L, INV",
    ]),
    "X": _box("HELP: EXAMINE (X)", [
        "  Examine an item or NPC in detail.",
        "  Usage: EXAMINE <target>  (or X <target>)",
        "  Examples:",
        "    EXAMINE sword",
        "    X gareth",
        "  See also: LOOK, L, INV",
    ]),
    "MOVE": _box("HELP: NORTH / SOUTH / EAST / WEST", [
        "  Move your party in the given direction.",
        "  Usage: NORTH / N, SOUTH / S, EAST / E, WEST / W",
        "  Details:",
        "    Moving costs 2 stamina per step.",
        "    Stamina 0 blocks movement until you rest.",
        "    Horses reduce stamina drain (HELP HORSES).",
        "  See also: LOOK, STAMINA, HORSES",
    ]),
    "INV": _box("HELP: INV / INVENTORY", [
        "  List all items carried by the party.",
        "  Usage: INV  (or INVENTORY)",
        "  Examples:",
        "    INV",
        "    INVENTORY",
        "  See also: EQUIP, UNEQUIP, DROP, TAKE, WEIGHT",
    ]),
    "INVENTORY": _box("HELP: INV / INVENTORY", [
        "  List all items carried by the party.",
        "  Usage: INV  (or INVENTORY)",
        "  Examples:",
        "    INV",
        "    INVENTORY",
        "  See also: EQUIP, UNEQUIP, DROP, TAKE, WEIGHT",
    ]),
    "EQUIP": _box("HELP: EQUIP", [
        "  Equip an item on a party member.",
        "  Usage: EQUIP <member> <item>  (or EQ <member> <item>)",
        "  Examples:",
        "    EQUIP Hero iron_sword",
        "    EQ Mira leather_armor",
        "  Details:",
        "    Equipping replaces whatever is in that slot.",
        "    Mages suffer spell power penalties for heavy armor.",
        "  See also: UNEQUIP, UNEQ, INV, WIZARD",
    ]),
    "EQ": _box("HELP: EQUIP (EQ)", [
        "  Equip an item on a party member.",
        "  Usage: EQUIP <member> <item>  (or EQ <member> <item>)",
        "  Examples:",
        "    EQUIP Hero iron_sword",
        "    EQ Mira leather_armor",
        "  See also: UNEQUIP, UNEQ, INV, WIZARD",
    ]),
    "UNEQUIP": _box("HELP: UNEQUIP", [
        "  Remove an equipped item from a slot.",
        "  Usage: UNEQUIP <member> <slot>  (or UNEQ <member> <slot>)",
        "  Examples:",
        "    UNEQUIP Hero weapon",
        "    UNEQ Mira body",
        "  Details:",
        "    Slots: weapon, body, head, hands, feet, back",
        "  See also: EQUIP, EQ, INV",
    ]),
    "UNEQ": _box("HELP: UNEQUIP (UNEQ)", [
        "  Remove an equipped item from a slot.",
        "  Usage: UNEQUIP <member> <slot>  (or UNEQ <member> <slot>)",
        "  Examples:",
        "    UNEQUIP Hero weapon",
        "    UNEQ Mira body",
        "  See also: EQUIP, EQ, INV",
    ]),
    "DROP": _box("HELP: DROP", [
        "  Drop an item from your inventory into the room.",
        "  Usage: DROP <item>",
        "  Examples:",
        "    DROP torch",
        "    DROP iron_sword",
        "  Details:",
        "    Dropped items remain in the room until picked up.",
        "  See also: TAKE, INV",
    ]),
    "TAKE": _box("HELP: TAKE / PICK", [
        "  Pick up an item from the current room.",
        "  Usage: TAKE <item>  (or PICK <item>)",
        "  Examples:",
        "    TAKE torch",
        "    PICK gold_coin",
        "  Details:",
        "    Check carry weight first — overloading slows movement.",
        "  See also: DROP, INV, WEIGHT",
    ]),
    "PICK": _box("HELP: TAKE / PICK", [
        "  Pick up an item from the current room.",
        "  Usage: TAKE <item>  (or PICK <item>)",
        "  Examples:",
        "    TAKE torch",
        "    PICK gold_coin",
        "  Details:",
        "    Check carry weight first — overloading slows movement.",
        "  See also: DROP, INV, WEIGHT",
    ]),
    "STATS": _box("HELP: STATS", [
        "  Show your character's statistics and attributes.",
        "  Usage: STATS",
        "  Details:",
        "    Shows STR, DEX, INT, WIS, CON and derived values.",
        "    Also shows HP, MP, XP, level, and equipped gear.",
        "  See also: SKILLS, SK, STATUS, SS, MODIFIERS",
    ]),
    "BUFFS": _box("HELP: BUFFS", [
        "  Show all active buffs and their effects on party members.",
        "  Usage: BUFFS  (or B)",
        "  Details:",
        "    Displays all temporary buffs currently affecting party members.",
        "    Includes duration and effect information for each buff.",
        "  See also: STATUS, SS, STATS",
    ]),
    "B": _box("HELP: BUFFS (B)", [
        "  Show all active buffs and their effects on party members.",
        "  Usage: BUFFS  (or B)",
        "  See also: STATUS, SS, STATS, BUFFS",
    ]),
    "BATTLELOOK": _box("HELP: BATTLELOOK", [
        "  Control whether a quick room summary is shown after combat ends.",
        "  Usage: BATTLELOOK ON | BATTLELOOK OFF",
        "",
        "  ON  — Show quick look after victory/defeat (default)",
        "  OFF — Show only the victory/defeat message",
        "",
        "  When ON, after combat ends you will see a compact room summary",
        "  showing items, enemies, NPCs, and other players in the room.",
        "",
        "  Your preference is saved with your character.",
        "",
        "  See also: LOOKMODE, LOOK",
    ]),
    "TALK": _box("HELP: TALK", [
        "  Talk to an NPC to start a conversation or quest.",
        "  Usage: TALK <npc_name>  (or T <npc_name>)",
        "  Examples:",
        "    TALK gareth",
        "    T gareth",
        "  See also: EXAMINE, X, NPCS",
    ]),
    "T": _box("HELP: TALK (T)", [
        "  Talk to an NPC to start a conversation or quest.",
        "  Usage: TALK <npc_name>  (or T <npc_name>)",
        "  See also: EXAMINE, X, TALK",
    ]),
    "DISMISS": _box("HELP: DISMISS", [
        "  Dismiss a hired NPC follower from your party.",
        "  Usage: DISMISS <npc_name>  (or DIS <npc_name>)",
        "  Examples:",
        "    DISMISS mercenary",
        "    DIS mercenary",
        "  See also: TALK, T, HIRE",
    ]),
    "DIS": _box("HELP: DISMISS (DIS)", [
        "  Dismiss a hired NPC follower from your party.",
        "  Usage: DISMISS <npc_name>  (or DIS <npc_name>)",
        "  See also: TALK, T, DISMISS",
    ]),
    "SAVE": _box("HELP: SAVE", [
        "  Save your character progress to the server.",
        "  Usage: SAVE  (or SV)",
        "  Details:",
        "    Saves character location, inventory, and progress.",
        "    Automatic saves occur periodically.",
        "  See also: QUIT, EXIT",
    ]),
    "SV": _box("HELP: SAVE (SV)", [
        "  Save your character progress to the server.",
        "  Usage: SAVE  (or SV)",
        "  See also: SAVE, QUIT, EXIT",
    ]),
    "UPGRADE": _box("HELP: UPGRADE", [
        "  Upgrade your character's skills or abilities.",
        "  Usage: UPGRADE  (or UPG)",
        "  Details:",
        "    Opens the upgrade menu for spending skill points.",
        "    Available at campfires or specific NPC locations.",
        "  See also: SKILLS, SK, LEARN, LRN",
    ]),
    "UPG": _box("HELP: UPGRADE (UPG)", [
        "  Upgrade your character's skills or abilities.",
        "  Usage: UPGRADE  (or UPG)",
        "  See also: SKILLS, SK, LEARN, LRN, UPGRADE",
    ]),
    "LEARN": _box("HELP: LEARN", [
        "  Learn new skills or spells from a trainer or book.",
        "  Usage: LEARN <skill>  (or LRN <skill>)",
        "  Examples:",
        "    LEARN fireball",
        "    LRN arcane_bolt",
        "  See also: SKILLS, SK, UPGRADE, UPG",
    ]),
    "LRN": _box("HELP: LEARN (LRN)", [
        "  Learn new skills or spells from a trainer or book.",
        "  Usage: LEARN <skill>  (or LRN <skill>)",
        "  See also: SKILLS, SK, UPGRADE, UPG, LEARN",
    ]),
    "DRINK": _box("HELP: DRINK", [
        "  Drink from a container or drinkable source to restore thirst.",
        "  Usage: DRINK <source>  (or DR <source>)",
        "  Examples:",
        "    DRINK waterskin",
        "    DR fountain",
        "  Details:",
        "    Restores thirst stat. Different sources provide different amounts.",
        "  See also: EAT, EA, THIRST, STATUS, SS",
    ]),
    "DR": _box("HELP: DRINK (DR)", [
        "  Drink from a container or drinkable source to restore thirst.",
        "  Usage: DRINK <source>  (or DR <source>)",
        "  See also: EAT, EA, THIRST, STATUS, SS, DRINK",
    ]),
    "EAT": _box("HELP: EAT", [
        "  Consume food items to restore hunger.",
        "  Usage: EAT <food>  (or EA <food>)",
        "  Examples:",
        "    EAT hard_bread",
        "    EA apple",
        "  Details:",
        "    Restores hunger stat. Different foods provide different amounts.",
        "  See also: DRINK, DR, HUNGER, STATUS, SS",
    ]),
    "EA": _box("HELP: EAT (EA)", [
        "  Consume food items to restore hunger.",
        "  Usage: EAT <food>  (or EA <food>)",
        "  See also: DRINK, DR, HUNGER, STATUS, SS, EAT",
    ]),
    "SKILLS": _box("HELP: SKILLS", [
        "  Show known skills and their effects.",
        "  Usage: SKILLS [COMBAT | UTILITY]  (or SK [COMBAT | UTILITY])",
        "  Examples:",
        "    SKILLS           — show all skills",
        "    SK               — same as SKILLS",
        "    SKILLS COMBAT    — show only combat skills",
        "  See also: STATS, LEARN, LRN",
    ]),
    "SK": _box("HELP: SKILLS (SK)", [
        "  Show known skills and their effects.",
        "  Usage: SKILLS [COMBAT | UTILITY]  (or SK [COMBAT | UTILITY])",
        "  Examples:",
        "    SKILLS           — show all skills",
        "    SK               — same as SKILLS",
        "  See also: STATS, LEARN, LRN",
    ]),
    "ATTACK": _box("HELP: ATTACK", [
        "  Engage in combat with hostile creatures in the room.",
        "  Usage: ATTACK [group]  (or K [group])",
        "  Examples:",
        "    ATTACK           — target the first hostile group",
        "    K                — same as ATTACK",
        "    ATTACK A         — target group A (Gauntlet arena)",
        "  Details:",
        "    Combat is automatic — your party fights by strategy.",
        "    Cannot attack in pitch black conditions.",
        "  Type HELP COMBAT for more on the combat system.",
        "  See also: COMBAT, STRATEGY, LIGHT, K",
    ]),
    "K": _box("HELP: ATTACK (K)", [
        "  Engage in combat with hostile creatures in the room.",
        "  Usage: ATTACK [group]  (or K [group])",
        "  Examples:",
        "    ATTACK           — target the first hostile group",
        "    K                — same as ATTACK",
        "    ATTACK A         — target group A (Gauntlet arena)",
        "  See also: COMBAT, STRATEGY, LIGHT, ATTACK",
    ]),
    "CAMP": _box("HELP: CAMP", [
        "  Enter campfire mode to rest and manage your party.",
        "  Usage: CAMP  (or CAMPFIRE)",
        "  Details:",
        "    At camp you can: REST, PARTY, STRATEGY, LEARN skills.",
        "    Type LEAVE to return to exploring.",
        "  See also: REST, PARTY, STRATEGY",
    ]),
    "STATUS": _box("HELP: STATUS", [
        "  Show party survival stats: hunger, thirst, and stamina.",
        "  Usage: STATUS  (or SS)",
        "  Details:",
        "    Survival bars drain over time and affect performance.",
        "    Use EAT, EA and DRINK, DR to restore hunger and thirst.",
        "    Use REST or SIT to recover stamina.",
        "  See also: HUNGER, THIRST, STAMINA, SURVIVAL, SS",
    ]),
    "SS": _box("HELP: STATUS (SS)", [
        "  Show party survival stats: hunger, thirst, and stamina.",
        "  Usage: STATUS  (or SS)",
        "  See also: HUNGER, THIRST, STAMINA, SURVIVAL, STATUS",
    ]),
    "SIT": _box("HELP: SIT / STAND", [
        "  Begin or end passive stamina recovery.",
        "  Usage: SIT   — sit down to slowly recover stamina",
        "         STAND — stand up and stop recovering",
        "  Details:",
        "    Sitting recovers stamina outside of combat.",
        "    You cannot move while sitting.",
        "    Full REST at campfire recovers much faster.",
        "  See also: STAMINA, REST",
    ]),
    "STAND": _box("HELP: SIT / STAND", [
        "  Begin or end passive stamina recovery.",
        "  Usage: SIT   — sit down to slowly recover stamina",
        "         STAND — stand up and stop recovering",
        "  Details:",
        "    Sitting recovers stamina outside of combat.",
        "    You cannot move while sitting.",
        "    Full REST at campfire recovers much faster.",
        "  See also: STAMINA, REST",
    ]),
    # ── Environment ───────────────────────────────────────────────────────────
    "TIME": _box("HELP: TIME", [
        "  Show the current in-game time, day number, and moon phase.",
        "  Usage: TIME  (or TI)",
        "  Details:",
        "    Time of day affects outdoor visibility (dawn/day/dusk/night).",
        "    Moon phase determines brightness on clear nights.",
        "  See also: WEATHER, WEA, LIGHT, ENVDETAILS",
    ]),
    "TI": _box("HELP: TIME (TI)", [
        "  Show the current in-game time, day number, and moon phase.",
        "  Usage: TIME  (or TI)",
        "  See also: WEATHER, WEA, LIGHT, ENVDETAILS, TIME",
    ]),
    "WEATHER": _box("HELP: WEATHER", [
        "  Show the current weather and temperature label.",
        "  Usage: WEATHER  (or WEA)",
        "  Details:",
        "    Weather only affects outdoor and indoor rooms.",
        "    Underground rooms are always the same temperature.",
        "    Weather changes gradually — a warning appears before it shifts.",
        "  See also: TIME, TI, LIGHT, ENVDETAILS",
    ]),
    "WEA": _box("HELP: WEATHER (WEA)", [
        "  Show the current weather and temperature label.",
        "  Usage: WEATHER  (or WEA)",
        "  See also: TIME, TI, LIGHT, ENVDETAILS, WEATHER",
    ]),
    "LIGHT": _box("HELP: LIGHT", [
        "  Show current lighting conditions and active light sources.",
        "  Usage: LIGHT  (or LIGHTING)",
        "  Details:",
        "    Light levels affect combat accuracy and dodge chance.",
        "    Pitch black rooms forbid player-initiated combat.",
        "    Use LIT <item> to light a torch or lantern.",
        "    Use EXTINGUISH <item> to put one out.",
        "  See also: LIT, EXTINGUISH, ENVDETAILS, COMBAT",
    ]),
    "LIGHTING": _box("HELP: LIGHT", [
        "  Show current lighting conditions and active light sources.",
        "  Usage: LIGHT  (or LIGHTING)",
        "  Details:",
        "    Light levels affect combat accuracy and dodge chance.",
        "    Pitch black rooms forbid player-initiated combat.",
        "    Use LIT <item> to light a torch or lantern.",
        "    Use EXTINGUISH <item> to put one out.",
        "  See also: LIT, EXTINGUISH, ENVDETAILS, COMBAT",
    ]),
    "ENVDETAILS": _box("HELP: ENVDETAILS", [
        "  Display full numeric environmental information.",
        "  Usage: ENVDETAILS  (or ENV)",
        "  Details:",
        "    Shows exact temperature, light percentages, moon phase, fuel remaining.",
        "  See also: TIME, WEATHER, LIGHT",
    ]),
    "ENV": _box("HELP: ENVDETAILS", [
        "  Display full numeric environmental information.",
        "  Usage: ENVDETAILS  (or ENV)",
        "  Details:",
        "    Shows exact temperature, light percentages, moon phase, fuel remaining.",
        "  See also: TIME, WEATHER, LIGHT",
    ]),
    "LIT": _box("HELP: LIT / EXTINGUISH", [
        "  Light a torch or lantern from your inventory.",
        "  Usage: LIT <item>",
        "  Examples:",
        "    LIT TORCH",
        "    LIT LANTERN",
        "  Details:",
        "    Torches burn for 60 game-minutes then go out automatically.",
        "    Lanterns require an Oil Flask to fill; they burn for 90 game-minutes.",
        "    ENVDETAILS shows fuel remaining.",
        "  See also: EXTINGUISH, LIGHT, ENVDETAILS",
    ]),
    "EXTINGUISH": _box("HELP: LIT / EXTINGUISH", [
        "  Put out a lit light source.",
        "  Usage: EXTINGUISH <item>  (or DOUSE <item>)",
        "  Examples:",
        "    EXTINGUISH TORCH",
        "    DOUSE LANTERN",
        "  Details:",
        "    Extinguishing preserves remaining fuel.",
        "  See also: LIT, LIGHT",
    ]),
    "DOUSE": _box("HELP: LIT / EXTINGUISH", [
        "  Put out a lit light source.",
        "  Usage: EXTINGUISH <item>  (or DOUSE <item>)",
        "  Examples:",
        "    EXTINGUISH TORCH",
        "    DOUSE LANTERN",
        "  Details:",
        "    Extinguishing preserves remaining fuel.",
        "  See also: LIT, LIGHT",
    ]),
    # ── Combat ────────────────────────────────────────────────────────────────
    "COMBAT": _box("HELP: COMBAT", [
        "  Combat is real-time and automatic. Your party acts on strategy rules.",
        "  Details:",
        "    Configure strategies at any campfire with STRATEGY <name> <tactic>.",
        "    Lighting affects accuracy and dodge chance:",
        "      Well-lit (80-100%) — no penalty",
        "      Good (60-80%)      — slight penalty",
        "      Dim (40-60%)       — moderate penalty",
        "      Dark (20-40%)      — heavy penalty",
        "      Very dark (5-20%)  — severe penalty",
        "      Pitch black (<5%)  — combat forbidden (your side)",
        "    Some creatures have Darkvision and ignore darkness penalties.",
        "  See also: ATTACK, FLEE, STRATEGY, LIGHT",
    ]),
    "FLEE": _box("HELP: FLEE", [
        "  Attempt to escape from combat.",
        "  Usage: FLEE",
        "  Details:",
        "    Fleeing costs 5 stamina.",
        "    Low stamina reduces your chance of fleeing successfully.",
        "    High DEX and SUPPORT/FLEE strategy improve flee odds.",
        "  See also: COMBAT, STRATEGY, STAMINA",
    ]),
    "STRATEGY": _box("HELP: STRATEGY", [
        "  Set a combat tactic for a party member or enemy.",
        "  Usage: STRATEGY <name> <tactic>",
        "  Tactics:",
        "    AGGRESSIVE — maximize damage output",
        "    DEFENSIVE  — reduce incoming damage, lower output",
        "    SUPPORT    — prioritize healing and buffs",
        "    FLEE       — attempt to flee on their turn",
        "  Examples:",
        "    STRATEGY Hero AGGRESSIVE",
        "    STRATEGY Mira DEFENSIVE",
        "  See also: COMBAT, FLEE",
    ]),
    "STRATEGIES": _box("HELP: STRATEGY", [
        "  Set a combat tactic for a party member or enemy.",
        "  Usage: STRATEGY <name> <tactic>",
        "  Tactics:",
        "    AGGRESSIVE — maximize damage output",
        "    DEFENSIVE  — reduce incoming damage, lower output",
        "    SUPPORT    — prioritize healing and buffs",
        "    FLEE       — attempt to flee on their turn",
        "  Examples:",
        "    STRATEGY Hero AGGRESSIVE",
        "    STRATEGY Mira DEFENSIVE",
        "  See also: COMBAT, FLEE",
    ]),
    "CAST": _box("HELP: CAST", [
        "  Cast a spell (mages only).",
        "  Usage: CAST <spell_id>",
        "  Examples:",
        "    CAST fireball",
        "    CAST frost_bolt",
        "  Details:",
        "    Casting costs MP and may take multiple ticks (cast time).",
        "    Being hit while casting may interrupt the spell.",
        "    Type HELP <spell_id> for details on a specific spell.",
        "  See also: SPELLS, WIZARD, CASTING",
    ]),
    # ── Campfire ──────────────────────────────────────────────────────────────
    "REST": _box("HELP: REST", [
        "  Rest the party at campfire to recover HP, MP, and stamina.",
        "  Usage: REST  (used in CAMPFIRE mode)",
        "  Details:",
        "    REST recovers full HP, MP, and stamina over time.",
        "    Bless Camp (cleric skill) boosts HP recovery rate.",
        "    Enter campfire mode with CAMP from NAVIGATION.",
        "  See also: CAMP, STAMINA, SIT",
    ]),
    "PARTY": _box("HELP: PARTY", [
        "  Show all party member status: HP, MP, survival stats.",
        "  Usage: PARTY  (or P)",
        "  Details:",
        "    PARTY works in NAVIGATION and CAMPFIRE states.",
        "    Shows survival aggregate row (hunger, thirst, stamina).",
        "  See also: STATUS, SS, STATS",
    ]),
    "P": _box("HELP: PARTY (P)", [
        "  Show all party member status: HP, MP, survival stats.",
        "  Usage: PARTY  (or P)",
        "  See also: STATUS, SS, STATS, PARTY",
    ]),
    # ── Survival ──────────────────────────────────────────────────────────────
    "HUNGER": _box("HELP: HUNGER", [
        "  Hunger drains over time and penalizes combat when critically low.",
        "  Details:",
        "    Hunger drains at a base rate each game tick.",
        "    At low hunger, your survival multiplier reduces damage dealt.",
        "    Use EAT <food> to restore hunger.",
        "  See also: THIRST, STAMINA, SURVIVAL, STATUS",
    ]),
    "THIRST": _box("HELP: THIRST", [
        "  Thirst drains faster in hot weather and penalizes combat.",
        "  Details:",
        "    Thirst drain rate scales with temperature (HELP WEATHER).",
        "    At low thirst, your survival multiplier reduces damage dealt.",
        "    Use DRINK <item> to restore thirst.",
        "  See also: HUNGER, STAMINA, SURVIVAL, STATUS",
    ]),
    "STAMINA": _box("HELP: STAMINA", [
        "  Stamina is consumed by movement and fleeing combat.",
        "  Details:",
        "    Each move costs 2 stamina (reduced by horses).",
        "    At stamina 0, movement is blocked.",
        "    FLEE costs 5 stamina.",
        "    Recovering: SIT to rest in place; REST at campfire for full recovery.",
        "  See also: HUNGER, THIRST, SURVIVAL, SIT, REST, HORSES",
    ]),
    "SURVIVAL": _box("HELP: SURVIVAL", [
        "  Overview of the three survival stats: Hunger, Thirst, Stamina.",
        "  Details:",
        "    Hunger — drains per tick; EAT to restore",
        "    Thirst — drains faster in heat; DRINK to restore",
        "    Stamina — drains on movement and FLEE; REST to restore",
        "    When Hunger or Thirst is critically low, combat damage is reduced.",
        "    Stamina 0 blocks movement entirely.",
        "  See also: HUNGER, THIRST, STAMINA, STATUS",
    ]),
    # ── Weight ────────────────────────────────────────────────────────────────
    "WEIGHT": _box("HELP: WEIGHT", [
        "  Carry weight affects movement stamina drain.",
        "  Details:",
        "    Your carry capacity is based on STR.",
        "    Carrying over the threshold increases stamina drain per step.",
        "    Check your current load with INV.",
        "  See also: INV, BACKPACK, CART, STAMINA",
    ]),
    "BACKPACK": _box("HELP: BACKPACK", [
        "  The backpack occupies the 'back' equipment slot.",
        "  Details:",
        "    Equip a backpack to increase carry capacity.",
        "    Usage: EQUIP <member> backpack",
        "  See also: EQUIP, WEIGHT, INV",
    ]),
    "CART": _box("HELP: CART", [
        "  A cart carries extra gear but is outdoor-only.",
        "  Details:",
        "    Load items into the cart with STASH <item>.",
        "    Retrieve items with UNLOAD <item>.",
        "    Cart items are inaccessible indoors or underground.",
        "  See also: STASH, UNLOAD, WEIGHT",
    ]),
    "GIVE": _box("HELP: GIVE", [
        "  Transfer an item between party members.",
        "  Usage: GIVE <item> <member>  (or GIV <item> <member>)",
        "  Examples:",
        "    GIVE torch Mira",
        "    GIV hard_bread Hero",
        "  See also: INV, EQUIP, EQ",
    ]),
    "GIV": _box("HELP: GIVE (GIV)", [
        "  Transfer an item between party members.",
        "  Usage: GIVE <item> <member>  (or GIV <item> <member>)",
        "  Examples:",
        "    GIVE torch Mira",
        "    GIV hard_bread Hero",
        "  See also: INV, EQUIP, EQ, GIVE",
    ]),
    "STASH": _box("HELP: STASH / LOAD", [
        "  Load an item into the party cart.",
        "  Usage: STASH <item>  (or LOAD <item>)",
        "  Details:",
        "    Cart is only accessible outdoors.",
        "    Use UNLOAD to retrieve items from the cart.",
        "  See also: CART, UNLOAD, WEIGHT",
    ]),
    "LOAD": _box("HELP: STASH / LOAD", [
        "  Load an item into the party cart.",
        "  Usage: STASH <item>  (or LOAD <item>)",
        "  Details:",
        "    Cart is only accessible outdoors.",
        "    Use UNLOAD to retrieve items from the cart.",
        "  See also: CART, UNLOAD, WEIGHT",
    ]),
    "UNLOAD": _box("HELP: UNLOAD", [
        "  Retrieve an item from the party cart.",
        "  Usage: UNLOAD <item>",
        "  Details:",
        "    Cart is only accessible outdoors.",
        "  See also: CART, STASH, WEIGHT",
    ]),
    # ── Mounts ────────────────────────────────────────────────────────────────
    "RIDE": _box("HELP: RIDE", [
        "  Mount the party's horses to reduce stamina drain while travelling.",
        "  Usage: RIDE",
        "  Details:",
        "    Requires at least one horse in the party's inventory.",
        "    Only works outdoors — horses wait outside indoor/underground rooms.",
        "    Stamina drain reduction scales with horse-to-party ratio.",
        "  See also: DISMOUNT, HORSES, STAMINA",
    ]),
    "DISMOUNT": _box("HELP: DISMOUNT", [
        "  Dismount the party's horses.",
        "  Usage: DISMOUNT",
        "  Details:",
        "    Horses wait in the last outdoor room and rejoin on return.",
        "  See also: RIDE, HORSES",
    ]),
    "HORSES": _box("HELP: HORSES", [
        "  Show party horse count and stamina reduction.",
        "  Usage: HORSES  (or HOR)",
        "  Details:",
        "    Stamina drain formula: 1 - (0.60 × horses / party_size)",
        "    Full mounted party (1 horse each) → 60% stamina reduction.",
        "  See also: RIDE, DISMOUNT, STAMINA, MOUNTS",
    ]),
    "HOR": _box("HELP: HORSES (HOR)", [
        "  Show party horse count and stamina reduction.",
        "  Usage: HORSES  (or HOR)",
        "  See also: RIDE, DISMOUNT, STAMINA, MOUNTS, HORSES",
    ]),
    "MOUNTS": _box("HELP: HORSES / MOUNTS", [
        "  Show party horse count and stamina reduction.",
        "  Usage: HORSES  (or MOUNTS)",
        "  Details:",
        "    Stamina drain formula: 1 - (0.60 × horses / party_size)",
        "    Full mounted party (1 horse each) → 60% stamina reduction.",
        "  See also: RIDE, DISMOUNT, STAMINA",
    ]),
    # ── Wizard ────────────────────────────────────────────────────────────────
    "WIZARD": _box("HELP: WIZARD (MAGE CLASS)", [
        "  The Mage class is a powerful glass cannon — high burst, fragile body.",
        "  Details:",
        "    Spells deal scaling damage based on INT and spell_power_modifier.",
        "    Wearing heavy armor reduces spell power (leather -10%, chain -30%, plate 0%).",
        "    Mages deal only 1 melee damage without a staff.",
        "    At 0 MP, mages can only DODGE — they cannot attack.",
        "    Staves preserve spell power and provide normal melee damage.",
        "  See also: SPELLS, CASTING, CAST, EQUIP",
    ]),
    "SPELLS": _box("HELP: SPELLS", [
        "  List of available mage spells with mana cost and cast time.",
        "  Spells:",
        "    ARCANE_BOLT     — quick single-target bolt (low MP)",
        "    MAGIC_MISSILE   — homing missile, moderate MP",
        "    FROST_BOLT      — single target, slowing effect",
        "    FIREBALL        — AoE fire damage",
        "    CHAIN_LIGHTNING — AoE lightning jumping between targets",
        "    ARCANE_SHIELD   — temporary damage reduction buff",
        "    BLINK           — teleport to avoid hits",
        "    ARCANE_LIGHT    — conjure magical light source",
        "    IDENTIFY        — reveal hidden item properties",
        "  Type HELP <spell_id> for details on any spell.",
        "  See also: CAST, CASTING, WIZARD",
    ]),
    "CASTING": _box("HELP: CASTING", [
        "  Cast times, interruption, and cancellation.",
        "  Details:",
        "    Some spells have a cast time (multiple ticks to complete).",
        "    Being hit while casting may interrupt the spell (wasting the cast).",
        "    High concentration resistance reduces interruption chance.",
        "    Cast: CAST <spell_id>",
        "  See also: CAST, SPELLS, WIZARD",
    ]),
    # ── Per-spell entries ─────────────────────────────────────────────────────
    "ARCANE_BOLT": _box("HELP: ARCANE_BOLT", [
        "  A quick bolt of arcane energy. Low cost, instant cast.",
        "  Usage: CAST arcane_bolt",
        "  Details:",
        "    Single target. Damage scales with INT.",
        "    Cast time: instant.",
        "  See also: SPELLS, CASTING, WIZARD",
    ]),
    "MAGIC_MISSILE": _box("HELP: MAGIC_MISSILE", [
        "  A homing missile of magical force. Never misses.",
        "  Usage: CAST magic_missile",
        "  Details:",
        "    Single target. Always hits (ignores dodge).",
        "    Damage scales with INT.",
        "  See also: SPELLS, CASTING, WIZARD",
    ]),
    "FROST_BOLT": _box("HELP: FROST_BOLT", [
        "  A bolt of freezing ice that chills the target.",
        "  Usage: CAST frost_bolt",
        "  Details:",
        "    Single target. Moderate MP cost.",
        "    Can reduce target movement / speed in future phases.",
        "  See also: SPELLS, CASTING, WIZARD",
    ]),
    "FIREBALL": _box("HELP: FIREBALL", [
        "  A ball of fire that explodes on impact, hitting all nearby enemies.",
        "  Usage: CAST fireball",
        "  Details:",
        "    AoE spell — damages all enemies in the target group.",
        "    High MP cost. Cast time: 1 tick.",
        "    Damage scales with INT and spell_power_modifier.",
        "  See also: SPELLS, CASTING, WIZARD, CHAIN_LIGHTNING",
    ]),
    "CHAIN_LIGHTNING": _box("HELP: CHAIN_LIGHTNING", [
        "  Lightning arcs between multiple enemies.",
        "  Usage: CAST chain_lightning",
        "  Details:",
        "    AoE spell — jumps between all enemies in range.",
        "    High MP cost. Damage scales with INT.",
        "  See also: SPELLS, CASTING, WIZARD, FIREBALL",
    ]),
    "ARCANE_SHIELD": _box("HELP: ARCANE_SHIELD", [
        "  Conjure a magical barrier that absorbs damage.",
        "  Usage: CAST arcane_shield",
        "  Details:",
        "    Buff — reduces incoming damage for the caster.",
        "    Duration: several ticks.",
        "  See also: SPELLS, CASTING, WIZARD",
    ]),
    "BLINK": _box("HELP: BLINK", [
        "  Teleport a short distance to avoid an attack.",
        "  Usage: CAST blink",
        "  Details:",
        "    Utility spell — provides a dodge chance boost.",
        "    Instant cast.",
        "  See also: SPELLS, CASTING, WIZARD",
    ]),
    "ARCANE_LIGHT": _box("HELP: ARCANE_LIGHT", [
        "  Conjure magical light, illuminating the area.",
        "  Usage: CAST arcane_light  (or USE arcane_light out of combat)",
        "  Details:",
        "    Provides light for 120 game-minutes.",
        "    Useful alternative to torches — requires no item.",
        "    Costs 15 MP.",
        "  See also: SPELLS, LIT, LIGHT, WIZARD",
    ]),
    "IDENTIFY": _box("HELP: IDENTIFY", [
        "  Reveal the hidden properties of an item.",
        "  Usage: USE identify  (utility skill, out of combat)",
        "  Details:",
        "    Costs 20 MP.",
        "    Use on unknown or magical items to learn their stats.",
        "  See also: SPELLS, SKILLS, WIZARD",
    ]),
    # ── Character Management ─────────────────────────────────────────────────
    "DELETE": _box("HELP: DELETE", [
        "  Permanently delete a character from the server.",
        "  Usage: DELETE <character_name>",
        "  Examples:",
        "    DELETE Aldric",
        "  Details:",
        "    This command is only available at the login screen.",
        "    You will be asked to confirm by typing the character name again.",
        "    This action is PERMANENT and cannot be undone!",
        "  To cancel: type CANCEL at the confirmation prompt.",
        "  See also: (available at login)",
    ]),
    # ── Multiplayer / Chat ────────────────────────────────────────────────────
    "SAY": _box("HELP: SAY", [
        "  Speak to all players in the same room.",
        "  Usage: SAY <message>  (or ' <message>)",
        "  Examples:",
        "    SAY Hello, traveler!",
        "    ' Hello, traveler!",
        "  Receivers see: [YourName says]: \"message\"",
        "  See also: EMOTE, ME, SHOUT, OOC, PLAYERS",
    ]),
    "'": _box("HELP: SAY (')", [
        "  Speak to all players in the same room.",
        "  Usage: SAY <message>  (or ' <message>)",
        "  Examples:",
        "    SAY Hello, traveler!",
        "    ' Hello, traveler!",
        "  See also: EMOTE, ME, SHOUT, OOC, PLAYERS, SAY",
    ]),
    "EMOTE": _box("HELP: EMOTE / ME", [
        "  Perform an emote visible to all players in the room.",
        "  Usage: EMOTE <action>  (or ME <action>)",
        "  Examples:",
        "    EMOTE waves cheerfully.",
        "    ME bows deeply.",
        "  Everyone in the room (including you) sees: * YourName action",
        "  See also: SAY, SHOUT",
    ]),
    "ME": _box("HELP: EMOTE / ME", [
        "  Perform an emote visible to all players in the room.",
        "  Usage: EMOTE <action>  (or ME <action>)",
        "  Examples:",
        "    EMOTE waves cheerfully.",
        "    ME bows deeply.",
        "  Everyone in the room (including you) sees: * YourName action",
        "  See also: SAY, SHOUT",
    ]),
    "SHOUT": _box("HELP: SHOUT / OOC", [
        "  Broadcast a message to all connected players regardless of room.",
        "  Usage: SHOUT <message>  (or OOC <message>)",
        "  Examples:",
        "    SHOUT Is anyone at the inn?",
        "  See also: SAY, EMOTE, PLAYERS",
    ]),
    "OOC": _box("HELP: SHOUT / OOC", [
        "  Broadcast a message to all connected players regardless of room.",
        "  Usage: SHOUT <message>  (or OOC <message>)",
        "  Examples:",
        "    OOC Anyone want to group up?",
        "  See also: SAY, EMOTE, PLAYERS",
    ]),
    "PLAYERS": _box("HELP: PLAYERS", [
        "  Shows who else is currently in your room.",
        "  Usage: LOOK  (other players appear under \"Also here:\")",
        "  Details:",
        "    Players in the same room can see each other's SAY and EMOTE messages.",
        "    Use SHOUT to reach players in other rooms.",
        "  See also: SAY, EMOTE, SHOUT, LOOK",
    ]),
    "MULTIPLAYER": _box("HELP: MULTIPLAYER", [
        "  Ashveil MUD supports multiple simultaneous players.",
        "  Key features:",
        "    - Other players appear in room descriptions (Also here: ...).",
        "    - Movement broadcasts: you see when others enter or leave.",
        "    - SAY — speak to your room.",
        "    - EMOTE / ME — perform an action visible to your room.",
        "    - SHOUT / OOC — broadcast to all players world-wide.",
        "  See also: SAY, EMOTE, SHOUT, PLAYERS",
    ]),
}


def _help_for_state(state) -> str:
    if state.value in ("connect", "creation"):
        return _box("HELP", [
            "  You are at the login screen. Available commands:",
            "",
            "    <character_name>  — Enter name to login or create a new character",
            "    DELETE <name>     — Permanently delete a character",
            "    HELP RACES        — Learn about available races",
            "    HELP CLASSES      — Learn about available classes",
            "    HELP DELETE       — Learn about character deletion",
            "",
            "  Type your responses as prompted.",
        ])
    elif state.value == "navigation":
        return _box("HELP", [
            "  You are exploring Ashveil. Available commands:",
            "",
            "    Movement     NORTH / N, SOUTH / S, EAST / E, WEST / W",
            "    Look         LOOK / L",
            "    Examine      EXAMINE / X",
            "    Inventory    INV / INVENTORY, EQUIP / EQ, UNEQUIP / UNEQ",
            "    Character    STATS, SKILLS / SK, STATUS / SS, BUFFS / B",
            "    Upgrade      UPGRADE / UPG, LEARN / LRN",
            "    Party        PARTY / P, TALK / T, DISMISS / DIS",
            "    Combat       ATTACK / K",
            "    Environment  TIME / TI, WEATHER / WEA, LIGHT, ENVDETAILS / ENV",
            "    Lighting     LIT <item>, EXTINGUISH / DOUSE",
            "    Camping      CAMP (enter campfire mode)",
            "    Survival     EAT / EA, DRINK / DR, SIT, SS",
            "    Communication SAY / ', EMOTE / ME, SHOUT / OOC",
            "    System       SAVE / SV, GIVE / GIV, HORSES / HOR",
            "",
            "  Type HELP <command> for details on any command.",
        ])
    elif state.value == "campfire":
        return _box("HELP", [
            "  You are resting at camp. Available commands:",
            "",
            "    REST             Rest the party (recovers HP, MP, stamina)",
            "    PARTY            Show party status",
            "    STRATEGY <name>  Set a combatant's strategy",
            "    LEAVE            Break camp and return to exploring",
            "",
            "  Type HELP <command> for details on any command.",
        ])
    elif state.value == "strategy":
        return _box("HELP", [
            "  You are setting combat strategies. Available commands:",
            "",
            "    STRATEGY <name> <tactic>   Set strategy for a party member",
            "    DONE                       Confirm strategies and return",
            "",
            "    Tactics: AGGRESSIVE, DEFENSIVE, SUPPORT, FLEE",
            "    Type HELP STRATEGY for full details.",
        ])
    elif state.value == "combat":
        return _box("HELP", [
            "  You are in combat. Available commands:",
            "",
            "    ATTACK <target>  Attack the named enemy",
            "    CAST <spell>     Cast a spell (mage only)",
            "    USE <item>       Use a consumable item",
            "    FLEE             Attempt to flee combat",
            "    PARTY            Show party HP/MP status",
            "",
            "  Battles are tick-based. Your strategy runs automatically.",
            "  Type HELP COMBAT for full details.",
        ])
    else:
        return _box("HELP", [
            "  Type HELP <command> for details on any command.",
            "  Type HELP for a list of available commands.",
        ])


async def send_help(send_fn, topic: str, state=None) -> None:
    """Look up a help topic and send the result via send_fn."""
    topic = topic.strip().upper()
    if not topic:
        if state is not None:
            await send_fn(_help_for_state(state))
        else:
            await send_fn(_box("HELP", ["  Type HELP <command> for details on any command."]))
    elif topic in _HELP_TOPICS:
        await send_fn(_HELP_TOPICS[topic])
    else:
        await send_fn(
            f"  No help found for '{topic}'. Type HELP to see available commands."
        )
